<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Gutenberg">
    <meta name="generator" content="http://www.mainpa.com">
    <title>Mainpa - Láminas y tableros</title>
	<link rel="icon" type="image/x-icon" href="img/favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/">
    <link href="assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/dist/css/style.css" rel="stylesheet">
    <link href="assets/dist/css/modal.css" rel="stylesheet">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet'>
	<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/brands.js" integrity="sha384-sCI3dTBIJuqT6AwL++zH7qL8ZdKaHpxU43dDt9SyOzimtQ9eyRhkG3B7KMl6AO19" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js" integrity="sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c" crossorigin="anonymous"></script>
    <style>
      body {
        font-family:'Comfortaa';
      }
    </style>
  </head>
  <body>
    <?php include 'bloques/cabecera.php'; ?>
    <div class="container d-flex align-items-center justify-content-center">
      <main class="pagina">
	    <article class="articulo mainpa-fondo-arboles">
          <h1 class="txt-center txt-blanco">Láminas y tableros</h1>
          <div class="row">
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modcaratula.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/caratula.jpg" alt="caratula" title="caratula"/>Carátula</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modmdf.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/mdf.jpg" alt="mdf" title="mdf"/>MDF</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modmdfranurado.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/mdf-ranurado.jpg" alt="mdf-ranurado" title="mdf-ranurado"/>MDF ranurado</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modmdp.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/mdp.jpg" alt="mdp" title="mdp"/>MDP</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modmedelack.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/medelack.jpg" alt="medelack" title="medelack"/>Medelack</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modmelamina.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/melamina.jpg" alt="melamina" title="melamina"/>Melamina</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modmotek.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/motek.jpg" alt="motek" title="motek"/>Motek</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modmultiplaca.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/multiplaca.jpg" alt="multiplaca2" title="multiplaca2"/>Multiplaca</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modosb.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/osb.jpg" alt="osb2" title="osb2"/>OSB</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modpinopanel.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/pino-panel.jpg" alt="pino-panel" title="pino-panel"/>Pino panel</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modtriplayokume.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/triplay-okume.jpg" alt="triplay-okume" title="triplay-okume"/>Triplay okume</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modtriplaybitangor.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/triplay-bitangor.jpg" alt="triplay-bitangor" title="triplay-bitangor"/>Triplay bitangor</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modtriplaypoplar.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/triplay-poplar.jpg" alt="triplay-poplar" title="triplay-poplar"/>Triplay poplar</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modtriplaylupuna.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/triplay-lupuna.jpg" alt="triplay-lupuna" title="triplay-lupuna"/>Triplay lupuna</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modtriplaycapinuri.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/triplay-capinuri.jpg" alt="triplay-capinuri" title="triplay-capinuri"/>Triplay capinuri</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modfenolicopino.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/fenolico-pino.jpg" alt="fenolico-pino" title="fenolico-pino"/>Fenolico pino</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modtriplaycedro.showModal();"><img class="img-producto div-border-radius" src="img/productos/laminas-tableros/triplay-cedro.jpg" alt="triplay-cedro" title="triplay-cedro"/>Triplay cedro</div></a></div>
          </div>
		</article>
      </main>
    </div>
    <?php include 'bloques/pie-pagina.php'; ?>
	<!-- inicio productos -->
    <dialog id="modcaratula" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Carátula</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/caratula.jpg" alt="caratula" title="caratula"/></div><div class="col-md-6"><p class="mod-titulo">Dubai Teverdoor<br><label class="mod-descripcion">Medidas: <br>- 87cm x 215cm<br>- 92cm x 215cm</label></p><p class="mod-titulo">Prestige Masonite<br><label class="mod-descripcion">Medidas: <br>- 82cm x 215cm</label></p><p class="mod-titulo">Sonata lisa Masonite<br><label class="mod-descripcion">Medidas: <br>- 67cm x 215cm<br>- 72cm x 215cm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modcaratula.close();">Cerrar</button></div></dialog>
    <dialog id="modmdf" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>MDF</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/mdf.jpg" alt="mdf" title="mdf"/></div><div class="col-md-6"><p class="mod-titulo">MDF 2130 x 2440<br><label class="mod-descripcion">Medidas: <br>- 2.5mm <br>- 3mm<br>- 4mm<br>- 5.5mm <br>- 9mm<br>- 12mm<br>- 15mm<br>- 18mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modmdf.close();">Cerrar</button></div></dialog>
    <dialog id="modmdfranurado" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>MDF ranurado</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/mdf-ranurado.jpg" alt="mdf-ranurado" title="mdf-ranurado"/></div><div class="col-md-6"><p class="mod-titulo">MDF ranurado blanco Arauco<br><label class="mod-descripcion">Medidas: <br>1.52m x 2.44m x 18mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modmdfranurado.close();">Cerrar</button></div></dialog>
    <dialog id="modmdp" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>MDP</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/mdp.jpg" alt="mdp" title="mdp"/></div><div class="col-md-6"><p class="mod-titulo">MDP 2130 x 2440<br><label class="mod-descripcion">Medidas: <br>- 18mm <br>- 15mm<br>- 12mm<br>- 10mm <br>- 8mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modmdp.close();">Cerrar</button></div></dialog>
    <dialog id="modmedelack" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Medelack</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/medelack.jpg" alt="medelack" title="medelack"/></div><div class="col-md-6"><p class="mod-titulo">MDF Medelack<br><label class="mod-descripcion">Medidas: <br>- 1.40m x 2.10m x 3mm<br>- 2.10m x 2.80m x 3mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modmedelack.close();">Cerrar</button></div></dialog>
    <dialog id="modmelamina" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Melamina</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/melamina.jpg" alt="melamina" title="melaminas"/></div><div class="col-md-6"><p class="mod-titulo">Melamina blanca<br><label class="mod-descripcion">Medidas: <br>- 2130mm x 2440mm x 18mm<br>- 2130mm x 2440mm x 15mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modmelamina.close();">Cerrar</button></div></dialog>
    <dialog id="modmotek" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Motek</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/motek.jpg" alt="motek" title="motek"/></div><div class="col-md-6"><p class="mod-titulo">Motek<br><label class="mod-descripcion">Medidas: <br>- 1.72m x 2.44m x 2.5mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modmotek.close();">Cerrar</button></div></dialog>
    <dialog id="modmultiplaca" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Multiplaca</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/multiplaca.jpg" alt="multiplaca" title="multiplaca"/></div><div class="col-md-6"><p class="mod-titulo">Eterboard<br><label class="mod-descripcion">Medidas: <br>- 1.22m x 2.44m x 10mm<br>- 1.22m x 2.44m x 8mm<br>- 1.22m x 2.44m x 6mm<br>- 1.22m x 2.44m x 4mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modmultiplaca.close();">Cerrar</button></div></dialog>
    <dialog id="modosb" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>OSB</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/osb.jpg" alt="osb" title="osb"/></div><div class="col-md-6"><p class="mod-titulo">OSB<br><label class="mod-descripcion">Medidas: <br>- 1220mm x 2440mm x 6mm<br>- 1220mm x 2440mm x 8mm<br>- 1220mm x 2440mm x 9mm<br>- 1220mm x 2440mm x 11mm<br>- 1220mm x 2440mm x 15mm<br>- 1220mm x 2440mm x 18mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modosb.close();">Cerrar</button></div></dialog>
    <dialog id="modpinopanel" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Pino panel</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/pino-panel.jpg" alt="pino-panel" title="pino-panel"/></div><div class="col-md-6"><p class="mod-titulo">Pino panel<br><label class="mod-descripcion">Medidas: <br>- 122mm x 244mm x 18mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modpinopanel.close();">Cerrar</button></div></dialog>
    <dialog id="modtriplayokume" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Triplay okume</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/triplay-okume.jpg" alt="triplay-okume" title="triplay-okume"/></div><div class="col-md-6"><p class="mod-titulo">Triplay okume<br><label class="mod-descripcion">Medidas: <br>- 700mm x 2100mm x 4mm<br>- 1220mm x 2440mm x 4mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modtriplayokume.close();">Cerrar</button></div></dialog>
    <dialog id="modtriplaybitangor" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Triplay bitangor</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/triplay-bitangor.jpg" alt="triplay-bitangor" title="triplay-bitangor"/></div><div class="col-md-6"><p class="mod-titulo">Triplay bitangor<br><label class="mod-descripcion">Medidas: <br>- 1220mm x 2440mm x 4mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modtriplaybitangor.close();">Cerrar</button></div></dialog>
    <dialog id="modtriplaypoplar" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Triplay poplar</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/triplay-poplar.jpg" alt="triplay-poplar" title="triplay-poplar"/></div><div class="col-md-6"><p class="mod-titulo">Triplay poplar<br><label class="mod-descripcion">Medidas: <br>- 1220mm x 2440mm x 3mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modtriplaypoplar.close();">Cerrar</button></div></dialog>
    <dialog id="modtriplaylupuna" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Triplay lupuna</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/triplay-lupuna.jpg" alt="triplay-lupuna" title="triplay-lupuna"/></div><div class="col-md-6"><p class="mod-titulo">Triplay lupuna<br><label class="mod-descripcion">Medidas: <br>- 1220mm x 2440mm x 4mm<br>- 1220mm x 2440mm x 6mm<br>- 1220mm x 2440mm x 8mm<br>- 1220mm x 2440mm x 10mm<br>- 1220mm x 2440mm x 12mm<br>- 1220mm x 2440mm x 15mm<br>- 1220mm x 2440mm x 18mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modtriplaylupuna.close();">Cerrar</button></div></dialog>
    <dialog id="modtriplaycapinuri" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Triplay capinuri</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/triplay-capinuri.jpg" alt="triplay-capinuri" title="triplay-capinuri"/></div><div class="col-md-6"><p class="mod-titulo">Triplay capinuri<br><label class="mod-descripcion">Medidas: <br>- 1220mm x 2440mm x 4mm<br>- 1220mm x 2440mm x 6mm<br>- 1220mm x 2440mm x 8mm<br>- 1220mm x 2440mm x 10mm<br>- 1220mm x 2440mm x 12mm<br>- 1220mm x 2440mm x 15mm<br>- 1220mm x 2440mm x 18mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modtriplaycapinuri.close();">Cerrar</button></div></dialog>
    <dialog id="modfenolicopino" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Fenólico pino</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/fenolico-pino.jpg" alt="fenolico-pino" title="fenolico-pino"/></div><div class="col-md-6"><p class="mod-titulo">Fenólico pino<br><label class="mod-descripcion">Medidas: <br>- 1220mm x 2440mm x 6mm<br>- 1220mm x 2440mm x 8mm<br>- 1220mm x 2440mm x 10mm<br>- 1220mm x 2440mm x 12mm<br>- 1220mm x 2440mm x 15mm<br>- 1220mm x 2440mm x 18mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modfenolicopino.close();">Cerrar</button></div></dialog>
    <dialog id="modtriplaycedro" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Triplay cedro</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/triplay-cedro.jpg" alt="triplay-cedro" title="triplay-cedro"/></div><div class="col-md-6"><p class="mod-titulo">Triplay cedro<br><label class="mod-descripcion">Medidas: <br>- 1220mm x 2440mm x 4mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modtriplaycedro.close();">Cerrar</button></div></dialog>
	<!-- fin productos -->
  </body>
</html>