<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Gutenberg">
    <meta name="generator" content="http://www.mainpa.com">
    <title>Mainpa - Madera</title>
	<link rel="icon" type="image/x-icon" href="img/favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/">
    <link href="assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/dist/css/style.css" rel="stylesheet">
    <link href="assets/dist/css/modal.css" rel="stylesheet">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet'>
	<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/brands.js" integrity="sha384-sCI3dTBIJuqT6AwL++zH7qL8ZdKaHpxU43dDt9SyOzimtQ9eyRhkG3B7KMl6AO19" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js" integrity="sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c" crossorigin="anonymous"></script>
    <style>
      body {
        font-family:'Comfortaa';
      }
    </style>
  </head>
  <body>
    <?php include 'bloques/cabecera.php'; ?>
    <div class="container d-flex align-items-center justify-content-center">
      <main class="pagina">
	    <article class="articulo mainpa-fondo-arboles">
          <h1 class="txt-center txt-blanco">Maderas</h1>
          <div class="row">
		    <div class="col-12 div-producto txt-blanco pad-10">MADERAS NACIONALES PARA CONSTRUCCIÓN</div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modroble.showModal();"><img class="img-producto div-border-radius" src="img/productos/maderas/roble.jpg" alt="roble" title="roble"/>Roble</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modcumala.showModal();"><img class="img-producto div-border-radius" src="img/productos/maderas/cumala.jpg" alt="cumala" title="cumala"/>Cumala</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modpashaco.showModal();"><img class="img-producto div-border-radius" src="img/productos/maderas/pashaco.jpg" alt="pashaco" title="pashaco"/>Pashaco</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modcapinuri.showModal();"><img class="img-producto div-border-radius" src="img/productos/maderas/capinuri.jpg" alt="capinuri" title="capinuri"/>Capinuri</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modcatahua.showModal();"><img class="img-producto div-border-radius" src="img/productos/maderas/catahua.jpg" alt="catahua" title="catahua"/>Catahua</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modmarupa.showModal();"><img class="img-producto div-border-radius" src="img/productos/maderas/marupa.jpg" alt="marupa" title="marupa"/>Marupa</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modcapirona.showModal();"><img class="img-producto div-border-radius" src="img/productos/maderas/capirona.jpg" alt="capirona" title="capirona"/>Capirona</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modcachimbo.showModal();"><img class="img-producto div-border-radius" src="img/productos/maderas/cachimbo.jpg" alt="cachimbo" title="cachimbo"/>Cachimbo</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modtornillo.showModal();"><img class="img-producto div-border-radius" src="img/productos/maderas/tornillo.jpg" alt="tornillo" title="tornillo"/>Tornillo</div></a></div>
            <div class="col-12 div-producto txt-blanco pad-10">MADERAS NACIONALES PARA ACABADOS</div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modcedro.showModal();"><img class="img-producto div-border-radius" src="img/productos/maderas/cedro.jpg" alt="cedro" title="cedro"/>Cedro</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modtornillo2.showModal();"><img class="img-producto div-border-radius" src="img/productos/maderas/tornillo.jpg" alt="tornillo" title="tornillo"/>Tornillo</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modhuayruro.showModal();"><img class="img-producto div-border-radius" src="img/productos/maderas/huayruro.jpg" alt="huayruro" title="huayruro"/>Huayruro</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modcapirona2.showModal();"><img class="img-producto div-border-radius" src="img/productos/maderas/capirona.jpg" alt="capirona" title="capirona"/>Capirona</div></a></div>
            <div class="col-12 div-producto txt-blanco pad-10">MADERA IMPORTADA</div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modpino.showModal();"><img class="img-producto div-border-radius" src="img/productos/maderas/pino.jpg" alt="pino" title="pino"/>Pino</div></a></div>
		  </div>
		</article>
      </main>
    </div>
    <?php include 'bloques/pie-pagina.php'; ?>
	<!-- inicio productos -->
    <dialog id="modroble" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Roble</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/maderas/roble.jpg" alt="roble" title="roble"/></div><div class="col-md-6"><p class="mod-titulo">Roble<br><label class="mod-descripcion">Madera para tablas de construcción, tablones, parantes, vigas, soleras y listones.<br><br>Medidas: <br>- 8 pies de largo.<br>- 10 pies de largo.</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modroble.close();">Cerrar</button></div></dialog>	
    <dialog id="modcumala" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Cumala</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/maderas/cumala.jpg" alt="cumala" title="cumala"/></div><div class="col-md-6"><p class="mod-titulo">Cumala<br><label class="mod-descripcion">Madera económica seca y derecha para listones de paneles, separación de ambientes, cercos perimétricos, letreros temporales y más.<br><br>Medidas: <br>- hasta 13 pies de largo.</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modcumala.close();">Cerrar</button></div></dialog>
    <dialog id="modpashaco" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Pashaco</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/maderas/pashaco.jpg" alt="pashaco" title="pashaco"/></div><div class="col-md-6"><p class="mod-titulo">Pashaco<br><label class="mod-descripcion">Madera para embalajes, parihuelas y más.<br><br>Medidas: <br>- hasta 12 pies de largo.</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modpashaco.close();">Cerrar</button></div></dialog>
    <dialog id="modcapinuri" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Capinuri</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/maderas/capinuri.jpg" alt="capinuri" title="capinuri"/></div><div class="col-md-6"><p class="mod-titulo">Capinuri<br><label class="mod-descripcion">Madera para embalajes, parihuelas y más.<br><br>Medidas: <br>- hasta 12 pies de largo.</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modcapinuri.close();">Cerrar</button></div></dialog>
    <dialog id="modcatahua" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Catahua</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/maderas/catahua.jpg" alt="catahua" title="catahua"/></div><div class="col-md-6"><p class="mod-titulo">Catahua<br><label class="mod-descripcion">Madera para embalajes, parihuelas y más.<br><br>Medidas: <br>- hasta 25 pies de largo.</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modcatahua.close();">Cerrar</button></div></dialog>
    <dialog id="modmarupa" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Marupa</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/maderas/marupa.jpg" alt="marupa" title="marupa"/></div><div class="col-md-6"><p class="mod-titulo">Marupa<br><label class="mod-descripcion">Madera para muebles rústicos, listones, tablas y más.<br><br>Medidas: <br>- hasta 13 pies de largo.</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modmarupa.close();">Cerrar</button></div></dialog>
    <dialog id="modcapirona" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Capirona</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/maderas/capirona.jpg" alt="capirona" title="capirona"/></div><div class="col-md-6"><p class="mod-titulo">Capirona<br><label class="mod-descripcion">Madera para vigas, bandas, parrillas y más.<br><br>Medidas: <br>- hasta 25 pies de largo.</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modcapirona.close();">Cerrar</button></div></dialog>
    <dialog id="modcachimbo" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Cachimbo</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/maderas/cachimbo.jpg" alt="cachimbo" title="cachimbo"/></div><div class="col-md-6"><p class="mod-titulo">Cachimbo<br><label class="mod-descripcion">Madera para diferentes tipos de trabajos como, vigas, tablas, marcos de puerta y más.<br><br>Medidas: <br>- hasta 25 pies de largo.</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modcachimbo.close();">Cerrar</button></div></dialog>
    <dialog id="modtornillo" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Tornillo</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/maderas/tornillo.jpg" alt="tornillo" title="tornillo"/></div><div class="col-md-6"><p class="mod-titulo">Tornillo<br><label class="mod-descripcion">Madera para tablas, vigas, marcos de puertas y más.<br><br>Medidas: <br>- hasta 25 pies de largo.</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modtornillo.close();">Cerrar</button></div></dialog>
    
    <dialog id="modcedro" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Cedro</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/maderas/cedro.jpg" alt="cedro" title="cedro"/></div><div class="col-md-6"><p class="mod-titulo">Cedro<br><label class="mod-descripcion">Madera de alta calidad para muebles y puertas de finos acabados.<br><br>Medidas: <br>- hasta 13 pies de largo.</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modcedro.close();">Cerrar</button></div></dialog>
    <dialog id="modtornillo2" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Tornillo</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/maderas/tornillo.jpg" alt="tornillo" title="tornillo"/></div><div class="col-md-6"><p class="mod-titulo">Tornillo<br><label class="mod-descripcion">Madera de buena calidad para puertas, muebles, marcos de puerta y más.<br><br>Medidas: <br>- hasta 25 pies de largo.</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modtornillo2.close();">Cerrar</button></div></dialog>
    <dialog id="modhuayruro" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Huayruro</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/maderas/huayruro.jpg" alt="huayruro" title="huayruro"/></div><div class="col-md-6"><p class="mod-titulo">Huayruro<br><label class="mod-descripcion">Madera de buena calidad para terrazas, techos sol y sombra y más.<br><br>Medidas: <br>- hasta 25 pies de largo.</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modhuayruro.close();">Cerrar</button></div></dialog>
    <dialog id="modcapirona2" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Capirona</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/maderas/capirona.jpg" alt="capirona" title="capirona"/></div><div class="col-md-6"><p class="mod-titulo">Capirona<br><label class="mod-descripcion">Madera para muebles, camas, bandas, parrillas y más.<br><br>Medidas: <br>- hasta 25 pies de largo.</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modcapirona2.close();">Cerrar</button></div></dialog>
    
    <dialog id="modpino" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Pino</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/laminas-tableros/pino.jpg" alt="pino" title="pino"/></div><div class="col-md-6"><p class="mod-titulo">Pino<br><label class="mod-descripcion">Medidas: <br>- 1'' x 2'' x 10.5'<br>- 2'' x 2'' x 10.5'<br>- 2'' x 3'' x 10.5'<br>- 1'' x 8'' x 10.5'<br>- 3/4'' x 8'' x 10.5'<br>- 2'' x 8'' x 10.5'</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modpino.close();">Cerrar</button></div></dialog>
	<!-- fin productos -->
  </body>
</html>
