<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Gutenberg">
    <meta name="generator" content="http://www.mainpa.com">
    <title>Mainpa - Techos</title>
	<link rel="icon" type="image/x-icon" href="img/favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/">
    <link href="assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/dist/css/style.css" rel="stylesheet">
    <link href="assets/dist/css/modal.css" rel="stylesheet">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet'>
	<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/brands.js" integrity="sha384-sCI3dTBIJuqT6AwL++zH7qL8ZdKaHpxU43dDt9SyOzimtQ9eyRhkG3B7KMl6AO19" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js" integrity="sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c" crossorigin="anonymous"></script>
    <style>
      body {
        font-family:'Comfortaa';
      }
    </style>
  </head>
  <body>
    <?php include 'bloques/cabecera.php'; ?>
    <div class="container d-flex align-items-center justify-content-center">
      <main class="pagina">
	    <article class="articulo mainpa-fondo-arboles">
          <h1 class="txt-center txt-blanco">Techos</h1>
          <div class="row">
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modcalaminagalv.showModal();"><img class="img-producto div-border-radius" src="img/productos/techos/calamina-galvanizada.jpg" alt="calamina-galvanizada" title="calamina-galvanizada"/>Calaminas galvanizadas</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modcalaminagalvroja.showModal();"><img class="img-producto div-border-radius" src="img/productos/techos/calamina-galvanizada-roja.jpg" alt="calamina-galvanizada-roja" title="calamina-galvanizada-roja"/>Calamina galvanizada prepintada roja</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modfibraforte.showModal();"><img class="img-producto div-border-radius" src="img/productos/techos/fibraforte.jpg" alt="fibraforte" title="fibraforte"/>Fibraforte</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modecotecho.showModal();"><img class="img-producto div-border-radius" src="img/productos/techos/ecotecho.jpg" alt="ecotecho" title="ecotecho"/>Ecotecho</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modtechoplus.showModal();"><img class="img-producto div-border-radius" src="img/productos/techos/techoplus.jpg" alt="techoplus" title="techoplus"/>Techoplus</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modtechito.showModal();"><img class="img-producto div-border-radius" src="img/productos/techos/techito.jpg" alt="techito" title="techito"/>Techito</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modeternit.showModal();"><img class="img-producto div-border-radius" src="img/productos/techos/eternit.jpg" alt="eternit" title="eternit"/>Eternit</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modtrapezoidal.showModal();"><img class="img-producto div-border-radius" src="img/productos/techos/trapezoidal.jpg" alt="trapezoidal" title="trapezoidal"/>Trapezoidal</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modaluzinc.showModal();"><img class="img-producto div-border-radius" src="img/productos/techos/aluzinc.jpg" alt="aluzinc" title="aluzinc"/>Aluzinc</div></a></div>
            <div class="col-6 col-sm-4 col-md-3 div-producto txt-center pad-10"><a href="#"><div class="div-border pad-20 div-border-radius bg-blanco open-modal" onclick="window.modtechoklar.showModal();"><img class="img-producto div-border-radius" src="img/productos/techos/techo-klar.jpg" alt="techo-klar" title="techo-klar"/>Techo Klar</div></a></div>
          </div>
		</article>
      </main>
    </div>
    <?php include 'bloques/pie-pagina.php'; ?>
	<!-- inicio productos -->
    <dialog id="modcalaminagalv" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Calaminas galvanizadas</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/techos/calamina-galvanizada.jpg" alt="calamina-galvanizada" title="calamina-galvanizada"/></div><div class="col-md-6"><p class="mod-titulo">Calaminas galvanizadas<br><label class="mod-descripcion">Medidas: <br>- 800 mm x 3600 mm x 0.14 mm<br> - 800 mm x 3600 mm x 0.18 mm<br> - 800 mm x 3600 mm x 0.20 mm<br> - 800 mm x 3600 mm x 0.22 mm<br> - 800 mm x 3600 mm x 0.30 mm<br> - 800 mm x 3000 mm x 0.14 mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modcalaminagalv.close();">Cerrar</button></div></dialog>
    <dialog id="modcalaminagalvroja" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Calamina galvanizada prepintada roja</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/techos/calamina-galvanizada-roja.jpg" alt="calamina-galvanizada-roja" title="calamina-galvanizada-roja"/></div><div class="col-md-6"><p class="mod-titulo">Calamina galvanizada prepintada roja<br><label class="mod-descripcion">Medidas: <br>- 800 mm x 3600 mm x 0.22 mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modcalaminagalvroja.close();">Cerrar</button></div></dialog>
    <dialog id="modfibraforte" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Fibraforte</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/techos/fibraforte.jpg" alt="fibraforte" title="fibraforte"/></div><div class="col-md-6"><p class="mod-titulo">Traslúcido<br><label class="mod-descripcion">Medidas: <br>- 1100 mm x 3050 mm</label></p><p class="mod-titulo">Rojo<br><label class="mod-descripcion">Medidas: <br>- 1100 mm x 3050 mm</label></p><p class="mod-titulo">Ambar<br><label class="mod-descripcion">Medidas: <br>- 1100 mm x 3050 mm</label></p><p class="mod-titulo">Gris<br><label class="mod-descripcion">Medidas: <br>- 1100 mm x 3050 mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modfibraforte.close();">Cerrar</button></div></dialog>
    <dialog id="modecotecho" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Ecotecho</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/techos/ecotecho.jpg" alt="ecotecho" title="ecotecho"/></div><div class="col-md-6"><p class="mod-titulo">Rojo<br><label class="mod-descripcion">Medidas: <br>- 1100 mm x 3000 mm</label></p><p class="mod-titulo">Rojo<br><label class="mod-descripcion">Medidas: <br>- 1100 mm x 3600 mm</label></p><p class="mod-titulo">Traslúcido<br><label class="mod-descripcion">Medidas: <br>- 1100 mm x 3000 mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modecotecho.close();">Cerrar</button></div></dialog>
    <dialog id="modtechoplus" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Techoplus</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/techos/techoplus.jpg" alt="techoplus" title="techoplus"/></div><div class="col-md-6"><p class="mod-titulo">Traslúcido<br><label class="mod-descripcion">Medidas: <br>- 800 mm x 3600 mm<br>- 1100 mm x 3050 mm</label></p><p class="mod-titulo">Rojo<br><label class="mod-descripcion">Medidas: <br>- 1100 mm x 3050 mm</label></p><p class="mod-titulo">Ambar<br><label class="mod-descripcion">Medidas: <br>- 800 mm x 3600 mm<br>- 1100 mm x 3050 mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modtechoplus.close();">Cerrar</button></div></dialog>
    <dialog id="modtechito" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Techito</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/techos/techito.jpg" alt="techito" title="techito"/></div><div class="col-md-6"><p class="mod-titulo">TR-4 Techito rojo<br><label class="mod-descripcion">Medidas: <br>- 1100 mm x 3600 mm x 1.5 mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modtechito.close();">Cerrar</button></div></dialog>
    <dialog id="modeternit" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Eternit</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/techos/eternit.jpg" alt="eternit" title="eternit"/></div><div class="col-md-6"><p class="mod-titulo">Gris<br><label class="mod-descripcion">Medidas: <br>- 1100 mm x 3050 mm</label></p><p class="mod-titulo">Rojo<br><label class="mod-descripcion">Medidas: <br>- 1100 mm x 3050 mm</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modeternit.close();">Cerrar</button></div></dialog>
    <dialog id="modtrapezoidal" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Trapezoidal</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/techos/trapezoidal.jpg" alt="trapezoidal" title="trapezoidal"/></div><div class="col-md-6"><p class="mod-titulo">TR6 Trapezoidal PP<br><label class="mod-descripcion">Medidas: <br>- 0.30 mm x 1050 mm x 3600 mm Azul<br>- 0.30 mm x 1050 mm x 3600 mm Rojo<br>- 0.30 mm x 1050 mm x 3600 mm Verde<br>- 0.25 mm x 900  mm x 2600 mm Rojo ladrillo<br>- 0.22 mm x 1050 mm x 3600 mm Rojo</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modtrapezoidal.close();">Cerrar</button></div></dialog>
    <dialog id="modaluzinc" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Aluzinc</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/techos/aluzinc.jpg" alt="aluzinc" title="aluzinc"/></div><div class="col-md-6"><p class="mod-titulo">Zincalum PV4 Gris<br><label class="mod-descripcion">Medidas: <br>- 0.30 mm x 1.04 m x 3.60 m<br>- 0.30 mm x 1.05 m x 6.00 m</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modaluzinc.close();">Cerrar</button></div></dialog>
    <dialog id="modtechoklar" class="col-12 bg-blanco mod-producto"><div class="row"><div class="col-md-12 pad-10"><h4>Techo Klar</h4></div></div><div class="row"><div class="col-md-6 div-border txt-center"><img class="img-modal" src="img/productos/techos/techo-klar.jpg" alt="techo-klar" title="techo-klar"/></div><div class="col-md-6"><p class="mod-titulo">H TK5 1.5 mm Termoacústico Rojo <br><label class="mod-descripcion">Medidas: <br>- 1.07 m x 3.60 m</label></p></div></div><div class="txt-right"><button class="close-modal" onclick="window.modtechoklar.close();">Cerrar</button></div></dialog>
	<!-- fin productos -->
  </body>
</html>
